name: Test and Deploy airflow dags

on:
  push:
    branches: [main, master]
    paths:
        - 'dags/**/*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          pip install pytest

      - name: Run tests
        run: pytest ./test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync files to server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          path: ./dags
          remote_path: /home/github/airflow-v2/dags
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}